#!/usr/bin/env bash
#Install nginx on your web-01

# Update package index
apt-get update -y

# Install nginx
apt-get install nginx -y

ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start