#!/usr/bin/env bash
# Server-01 login commands

# Setting up the SSH agent
eval $("ssh-agent")

# Path to identityFile
ssh-add ~/ALX__SE/alx-system_engineering-devops/0x0B-ssh

# Username and IP Address 
ssh ubuntu@54.237.9.72
